[tool.poetry]
name = "timegrad"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
gluonts = "0.9.0"
mxnet = "^1.9.1"
pytorchts = "^0.6.0"
ipykernel = "^6.19.4"
numpy = "1.21.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
